[package]
name = "genee"
version = "0.4.1"
authors = ["Lőrinc Serfőző <lorinc.serfozo@mailbox.org>"]
edition = "2018"
default-run = "genee"
description = "A habit tracker app with command-line interface"
license = "MIT"
homepage = "https://github.com/mfep/genee"
readme = "README.md"
repository = "https://github.com/mfep/genee"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
anyhow = "1.0"
structopt = "0.3.21"
yansi = "0.5.0"
rand = "0.8.3"
confy = "0.4"
directories-next = "2.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
dialoguer = "0.9"
