[package]
name = "genee"
version = "0.1.0"
authors = ["lorinc"]
edition = "2018"
default-run = "genee"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
anyhow = "1.0"
structopt = "0.3.21"
yansi = "0.5.0"
rand = "0.8.3"
