[package]
name = "genee"
version = "0.1.0"
authors = ["lorinc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
anyhow = "1.0"
human-panic = "1.0.3"
structopt = "0.3.21"
